name: Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb: # Set up Xvfb to run the tests in a virtual display
        image: "selenium/standalone-chrome"
        options: --privileged

    strategy:
      matrix:
        browser: [chromium] # You can add firefox, webkit if you want to run on other browsers too

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the version you are working with

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: xvfb-run --auto-servernum npx playwright test --project=${{ matrix.browser }}
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/