name: Playwright Tests

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest



    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # action to pull the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3   required to run your Playwright tests
      with:
        node-version: 18 

    - name: Install dependencies
      run: npm ci  # Use npm ci to install the exact versions from package-lock.json

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps  # Install the necessary browsers and dependencies

    - name: Run Playwright Tests
      run: npx playwright test --reporter=dot
